<a href="https://colab.research.google.com/github/curryrice55/bert/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensorの生成

In [2]:
import torch

#create tensor from list
tensor_list = torch.tensor([1,2,3])
print(tensor_list, type(tensor_list))

tensor([1, 2, 3]) <class 'torch.Tensor'>


In [6]:
#create tensor from 2d list
tensor_2d_list = torch.tensor([[1,2],[3,4]])
print(tensor_2d_list, type(tensor_2d_list),tensor_2d_list.dtype)

#create tensor from 2d list (dtype=torch.float64)
tensor_2d_list = torch.tensor([[1,2],[3,4]],dtype=torch.float64)
print(tensor_2d_list, type(tensor_2d_list),tensor_2d_list.dtype)

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'> torch.int64
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64) <class 'torch.Tensor'> torch.float64


In [11]:
print("---tensor inits from 0 to 9---")
print(torch.arange(0,10))

print("---2 x 3tensor with all 0---")
print(torch.zeros(2,3))

print("---2 x 3tensor with rand num---")
print(torch.rand(2,3))

---tensor inits from 0 to 9---
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
---2 x 3tensor with all 0---
tensor([[0., 0., 0.],
        [0., 0., 0.]])
---2 x 3tensor with rand num---
tensor([[0.4195, 0.4026, 0.5145],
        [0.7291, 0.0069, 0.2750]])


In [13]:
print("---create 10 elements from -5 to 5---")
print(torch.linspace(-5,5,10))

---create 10 elements from -5 to 5---
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


view()によるTensor形状の変換

In [15]:
a = torch.arange(0,8) #1次元のTensor
print(a)
b = a.view(2,4) #(2,4)の2次元のTensorに変換
print(b)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
